=== zodiia/zapi/src/main/resources/kotlin-plugin-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "JSON schema for zApi Kotlin plugins.",
  "type": "object",
  "additionalProperties": false,
  "definitions": {
    "dependency": {
      "": "",
      "type": "string"
    },
    "url": {
      "type": "string",
      "pattern": "https?://[-a-zA-Z0-9@:%._+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b[-a-zA-Z0-9()@:%_+.~#?&/=]*"

    },
    "defaultPermission": {
      "enum": [true, false, "op", "not-op"]
    },
    "permission": {
      "description": "A permission node.",
      "anyOf": [
        {
          "$ref": "#/definitions/defaultPermission"
        },
        {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/permission"
          }
        }
      ]
    }
  },
  "required": ["apiVersion", "minecraftVersion", "main"],
  "properties": {
    "pluginDependencies": {
      "description": "List of required plugin dependencies, with specific versions.",
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "description": "A required plugin dependency. More information about the version range format: https://github.com/npm/node-semver."
      }
    },
    "softPluginDependencies": {
      "description": "List of optional plugin dependencies, with specific versions.",
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "description": "An optional plugin dependency. More information about the version range format: https://github.com/npm/node-semver."
      }
    },
    "minecraftVersion": {
      "description": "Required Minecraft version to run the plugin. More information about the version range format: https://github.com/npm/node-semver.",
      "type": "string"
    },
    "files": {
      "description": "List of configuration files (or any other type) to save into the plugin's directory.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "urls": {
      "description": "A list of URLs for this project.",
      "type": "object",
      "properties": {
        "bugs": {
          "description": "URL to a bug report page.",
          "$ref": "#/definitions/url"
        },
        "homepage": {
          "description": "URL to the project's homepage.",
          "$ref": "#/definitions/url"
        },
        "docs": {
          "description": "URL to the project's documentation.",
          "$ref": "#/definitions/url"
        },
        "repository": {
          "description": "URL to the project's repository.",
          "$ref": "#/definitions/url"
        }
      }
    },
    "spigotId": {
      "description": "Spigot project ID.",
      "type": "number"
    },
    "main": {
      "description": "Main plugin class.",
      "type": "string"
    },
    "description": {
      "description": "Plugin's description.",
      "type": "string"
    },
    "authors": {
      "description": "List of plugin's authors.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "load": {
      "description": "The phase of server-startup this plugin will load during.",
      "type": "string",
      "enum": ["STARTUP", "POSTWORLD"]
    },
    "apiVersion": {
      "description": "Gives the API version which this plugin is designed to support.",
      "type": "string",
      "pattern": "^1\\.\\d+$"
    },
    "permissions": {
      "$ref": "#/definitions/permission"
    },
    "defaultPermission": {
      "$ref": "#/definitions/defaultPermission"
    }
  }
}

=== zodiia/zapi/src/main/resources/kotlinPlugin.json
{
  "minecraftVersion": ">1.16.5",
  "apiVersion": "1.17",
  "main": "me.zodiia.api.ApiPlugin",
  "pluginDependencies": {},
  "softPluginDependencies": {
    "PlaceholderAPI": ">=2.9",
    "Vault": ">=1.7.2"
  },
  "files": [],
  "spigotId": -1,
  "urls": {
    "bugs": "https://gitlab.com/manon.grivot/zapi/-/issues",
    "docs": "https://zodiia.moe/zapi/docs",
    "homepage": "https://zodiia.moe/zapi",
    "repository": "https://gitlab.com/manon.grivot/zapi"
  },
  "permissions": {
    "api.*": {
      "api.test": "op"
    },
    "api": true
  },
  "defaultPermission": "op",
  "description": "zApi is an utility API for all of Zodiia's plugins.",
  "authors": ["Zodiia"],
  "load": "STARTUP"
}
